version: '2.2'

services:
  mongodb-primary:
    image: docker.io/bitnami/mongodb:latest
    ports:
      - 30001:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_NAME=replicasetName
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=rootpass
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - ./../mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:latest
    ports:
      - 30002:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_NAME=replicasetName
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=rootpass
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:latest
    ports:
      - 30003:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_NAME=replicasetName
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=rootpass
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

#      - MONGODB_ADVERTISED_HOSTNAME=localhost #localhost docker hack

  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootpass
      - MINIO_DEFAULT_BUCKETS=buysell
    volumes:
      - 'minio_data:/bitnami/minio/data'

  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=keycloak_pwd
      - POSTGRESQL_DATABASE=keycloak
#    volumes:
#      - 'postgresql_data:/bitnami/postgresql'

  #https://hub.docker.com/r/bitnami/keycloak
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak_pwd
      - KEYCLOAK_EXTRA_ARGS=--import-realm
    depends_on:
      - postgresql
    volumes:
      - ./../keycloak/realms:/opt/bitnami/keycloak/data/import
#      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'

volumes:
  mongodb-data:
    driver: local
  minio_data:
    driver: local
  postgresql_data:
    driver: local