version: '1'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - ./../mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      - mongodb-data:/data/db

  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootpass
      - MINIO_DEFAULT_BUCKETS=buysell
    volumes:
      - 'minio_data:/bitnami/minio/data'

volumes:
  mongodb-data:
    driver: local
  minio_data:
    driver: local

#networks:
#  default:
#    name: mongodb_network


