server:
  port: 8082

spring:
  application:
    name: "admin"
  config:
    import: "configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "admin"
    description: "admin desc"
    version: "1.0.0"