server:
  port: 8088

spring:
  application:
    name: "emails"
  config:
    import: "optional:configserver:http://localhost:8071"
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
  mail:
    host: localhost
    protocol: smtp
    from: support@buysell.com
    username: dummy
    password: dummy
    port: 1025
    properties:
      mail:
        smtp:
          starttls:
            enable: false
          auth: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "emails"
    description: "emails desc"
    version: "1.0.0"