server:
  port: 8081

spring:
  application:
    name: "attachments"
  config:
    import: "configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "attachments"
    description: "attachments desc"
    version: "1.0.0"